=== votrongdao/UQ-iLab-BatchLabServer/TimeOfDay/LabServer/App_Data/LabConfiguration.dtd
<!ELEMENT labConfiguration (navmenuPhoto, labCamera, labInfo, configuration, experimentSpecification, experimentResult, resultsApplet)>
<!ATTLIST labConfiguration title CDATA #REQUIRED version CDATA #REQUIRED>

<!ELEMENT navmenuPhoto (image)>
<!ELEMENT labCamera (url)>
<!ELEMENT labInfo (text, url)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT url (#PCDATA)>


<!ELEMENT configuration (setup+, timeServers, timeFormats)>
<!ELEMENT setup (name, description)>
<!ATTLIST setup id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (p*)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT timeServers (url*)>
<!ELEMENT timeFormats (timeFormat+)>
<!ATTLIST timeFormats default CDATA #REQUIRED>
<!ELEMENT timeFormat (#PCDATA)>

<!ELEMENT experimentSpecification (setupId, serverUrl, formatName)>
<!ELEMENT setupId (#PCDATA)>
<!ELEMENT serverUrl (#PCDATA)>
<!ELEMENT formatName (#PCDATA)>

<!ELEMENT experimentResult (timestamp, title, version, experimentId, unitId, setupId, setupName, serverUrl, formatName,
  timeofday, dayofweek, day, month, year, hours, minutes, seconds)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT experimentId (#PCDATA)>
<!ELEMENT unitId (#PCDATA)>
<!ELEMENT setupName (#PCDATA)>
<!ELEMENT timeofday (#PCDATA)>
<!ELEMENT dayofweek (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT minutes (#PCDATA)>
<!ELEMENT seconds (#PCDATA)>

<!ELEMENT resultsApplet (archive, code)>
<!ELEMENT archive (#PCDATA)>
<!ELEMENT code (#PCDATA)>

=== votrongdao/UQ-iLab-BatchLabServer/TimeOfDay/LabServer/App_Data/LabConfiguration.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!--<!DOCTYPE labConfiguration SYSTEM "LabConfiguration.dtd">-->
<labConfiguration title="Time-Of-Day" version="3.1">
  <navmenuPhoto>
    <image>~/images/sundial.jpg</image>
  </navmenuPhoto>
  <labCamera>
    <url />
  </labCamera>
  <labInfo>
    <text>UQ iLab Projects - Time-Of-Day</text>
    <url>http://icampus.uq.edu.au/projects/ilab/_batch_timeofday/index.php</url>
  </labInfo>
  <configuration>
    <setup id="LocalClock">
      <name>Local Time</name>
      <description>
        <p>Obtain the date and time from the LabServer's computer clock.</p>
      </description>
    </setup>
    <setup id="NTPServer">
      <name>Network Time</name>
      <description>
        <p>Obtain the date and time from a Network Time Prototocol (NTP) server on the internet.</p>
      </description>
    </setup>
    <timeServers>
      <url>localhost</url>
      <url>cuscus.cc.uq.edu.au</url>
      <url>ntp0.broad.mit.edu</url>
      <url>url.does.not.exist</url>
    </timeServers>
    <timeFormats default="12-Hour">
      <timeFormat>12-Hour</timeFormat>
      <timeFormat>24-Hour</timeFormat>
    </timeFormats>
  </configuration>
  <experimentSpecification>
    <setupId />
    <serverUrl />
    <formatName />
  </experimentSpecification>
  <experimentResult>
    <timestamp />
    <title />
    <version />
    <experimentId />
    <unitId />
    <setupId />
    <setupName />
    <serverUrl />
    <formatName />
    <timeofday />
    <dayofweek />
    <day />
    <month />
    <year />
    <hours />
    <minutes />
    <seconds />
  </experimentResult>
  <resultsApplet>
    <archive>Applets/TimeOfDayResults.jar</archive>
    <code>src/ResultsApplet.class</code>
  </resultsApplet>
</labConfiguration>
