=== votrongdao/UQ-iLab-BatchLabServer/Template/LabServer/App_Data/LabConfiguration.dtd
<!ELEMENT labConfiguration (navmenuPhoto, labCamera, labInfo, configuration, validation, experimentSpecification, experimentResult, resultsApplet)>
<!ATTLIST labConfiguration title CDATA #REQUIRED version CDATA #REQUIRED>

<!ELEMENT navmenuPhoto (image)>
<!ELEMENT labCamera (url)>
<!ELEMENT labInfo (text, url)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT configuration (setup+)>
<!ELEMENT setup (name, description)>
<!ATTLIST setup id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (p*)>
<!ELEMENT p (#PCDATA)>
<!-- YOUR CODE HERE -->

<!ELEMENT validation (#PCDATA)>

<!ELEMENT experimentSpecification (setupId)>
<!ELEMENT setupId (#PCDATA)>
<!-- YOUR CODE HERE -->

<!ELEMENT experimentResult (timestamp, title, version, experimentId, unitId, setupId, setupName)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT experimentId (#PCDATA)>
<!ELEMENT unitId (#PCDATA)>
<!ELEMENT setupName (#PCDATA)>
<!-- YOUR CODE HERE -->

<!ELEMENT resultsApplet (archive, code)>
<!ELEMENT archive (#PCDATA)>
<!ELEMENT code (#PCDATA)>

=== votrongdao/UQ-iLab-BatchLabServer/Template/LabServer/App_Data/LabConfiguration.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!--<!DOCTYPE labConfiguration SYSTEM "LabConfiguration.dtd">-->
<labConfiguration title="Template" version="3.2">
  <navmenuPhoto>
    <image>~/images/generic_content32.jpg</image>
  </navmenuPhoto>
  <labCamera>
    <url />
  </labCamera>
  <labInfo>
    <text />
    <url />
  </labInfo>
  <configuration>
    <setup id="Equipment">
      <name>Setup for Equipment</name>
      <description>
        <p>Template setup for driving equipment.</p>
      </description>
    </setup>
    <setup id="Simulation">
      <name>Setup for Simulation</name>
      <description>
        <p>Template setup for running a simulation.</p>
      </description>
    </setup>
    <!-- YOUR CODE HERE -->
  </configuration>
  <validation>
    <!-- YOUR CODE HERE -->
  </validation>
  <experimentSpecification>
    <setupId />
    <!-- YOUR CODE HERE -->
  </experimentSpecification>
  <experimentResult>
    <timestamp />
    <title />
    <version />
    <experimentId />
    <unitId />
    <setupId />
    <setupName />
    <!-- YOUR CODE HERE -->
  </experimentResult>
  <resultsApplet>
    <archive></archive>
    <code></code>
  </resultsApplet>
</labConfiguration>
